#ifndef MECANUM_MIXER_H
#define MECANUM_MIXER_H

#include <stdint.h>
#include "car_config.h"

/*
 * Logical wheel order:
 *
 *       M1 front-left        M2 front-right
 *       M3 rear-left         M4 rear-right
 *
 * A positive strafe_right input is the command generated by the Android
 * "right strafe" control.  CAR_MECANUM_STRAFE_RIGHT_SIGN adapts that command
 * to the installed roller orientation.  It is deliberately applied here, at
 * the only place that computes individual wheel targets.
 */
static inline void CAR_MecanumMixVelocity(float forward_mps,
                                          float strafe_right_mps,
                                          float turn_left_rps,
                                          float wheel_mps[4])
{
  float normalized_strafe;
  float rotation_mps;

  normalized_strafe = strafe_right_mps * CAR_MECANUM_STRAFE_RIGHT_SIGN;
  rotation_mps = 0.5f * CAR_WHEEL_TRACK_M * turn_left_rps;

  wheel_mps[0] = forward_mps + normalized_strafe - rotation_mps;
  wheel_mps[1] = forward_mps - normalized_strafe + rotation_mps;
  wheel_mps[2] = forward_mps - normalized_strafe - rotation_mps;
  wheel_mps[3] = forward_mps + normalized_strafe + rotation_mps;
}

/* The direct motor API uses positive clockwise turn, unlike the protocol. */
static inline void CAR_MecanumMixCommand(int32_t forward,
                                         int32_t strafe_right,
                                         int32_t turn_clockwise,
                                         int32_t wheel[4])
{
  int32_t normalized_strafe;

  normalized_strafe = strafe_right * CAR_MECANUM_STRAFE_RIGHT_SIGN;
  wheel[0] = forward + normalized_strafe + turn_clockwise;
  wheel[1] = forward - normalized_strafe - turn_clockwise;
  wheel[2] = forward - normalized_strafe + turn_clockwise;
  wheel[3] = forward + normalized_strafe - turn_clockwise;
}

#endif /* MECANUM_MIXER_H */
